spring.application.name=Gateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.server.webflux.routes[0].id=ms-employees
spring.cloud.gateway.server.webflux.routes[0].uri=lb://employees
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/employees/**

spring.cloud.gateway.server.webflux.routes[1].id=ms-departments
spring.cloud.gateway.server.webflux.routes[1].uri=lb://departments
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/departments/**

spring.cloud.gateway.server.webflux.routes[2].id=ms-jobtitles
spring.cloud.gateway.server.webflux.routes[2].uri=lb://jobtitles
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/jobtitles/**

# CORS

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:4200
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allow-credentials=true